//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Predare
{
    using System;
    using System.Collections.Generic;
    
    public partial class acte
    {
        public acte()
        {
            this.istoric_cereri = new HashSet<istoric_cereri>();
        }
    
        public int id { get; set; }
        public string denumire { get; set; }
        public string continut { get; set; }
    
        public virtual ICollection<istoric_cereri> istoric_cereri { get; set; }
    }
}
