//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Predare
{
    using System;
    using System.Collections.Generic;
    
    public partial class level
    {
        public level()
        {
            this.personals = new HashSet<personal>();
            this.rules = new HashSet<rule>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<personal> personals { get; set; }
        public virtual ICollection<rule> rules { get; set; }
    }
}
