//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Predare
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acte> actes { get; set; }
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<istoric_cereri> istoric_cereri { get; set; }
        public virtual DbSet<level> levels { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<personal> personals { get; set; }
        public virtual DbSet<pontaje> pontajes { get; set; }
        public virtual DbSet<rule> rules { get; set; }
        public virtual DbSet<trainer> trainers { get; set; }
    }
}
