//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Predare
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public personal()
        {
            this.candidates = new HashSet<candidate>();
            this.employees = new HashSet<employee>();
            this.istoric_cereri = new HashSet<istoric_cereri>();
            this.logs = new HashSet<log>();
            this.pontajes = new HashSet<pontaje>();
            this.trainers = new HashSet<trainer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> phone { get; set; }
        public string address { get; set; }
        public Nullable<int> CNP { get; set; }
        public string email { get; set; }
        public string civilst { get; set; }
        public string depart { get; set; }
        public string sex { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public int id_level { get; set; }
    
        public virtual ICollection<candidate> candidates { get; set; }
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<istoric_cereri> istoric_cereri { get; set; }
        public virtual level level { get; set; }
        public virtual ICollection<log> logs { get; set; }
        public virtual ICollection<pontaje> pontajes { get; set; }
        public virtual ICollection<trainer> trainers { get; set; }
    }
}
